// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:3d252059-96c5-4c80-9d72-1aa4061390fa",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4Bw9XVPxx",
    "aws_user_pools_web_client_id": "38nqlnr8p7q7jcj4cbelrtlbel",
    "aws_mobile_analytics_app_id": "369b3a4ba6d34a0bb9350d3f6d24f472",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
